server:
  port: 8081

spring:
  application:
    name: bookpoint
  datasource:
    url: jdbc:postgresql://bookpoint_db:5432/bookpoint_db
    username: bookpoint_user
    password: bookpoint_password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  server:
    port: 8081

api:
  management:
    header: "X-MANAGEMENT-API"
    key: "bookpoint"
  internal:
    header: "X-INTERNAL-API"
    services:
      authpoint: "AUTH_POINT_INTERNAL_KEY"

web-clients:
  clients:
    achievepoint:
      destination: http://tochkaszapyatoi.ru:8083
      headers:
        X-INTERNAL-API: "BOOK_POINT_INTERNAL_KEY"

grpc:
  client:
    authpoint:
      address: static://tochkaszapyatoi.ru:9098
      negotiation-type: plaintext

jobs:
  reservationCheck:
    cron: "0 0 0 * * ?"
    enabled: true

kafka:
  topics:
    notification:
      destination: notifypoint.notifications
  clusters:
    default:
      bootstrap-servers:
        - tochkaszapyatoi.ru:29092
      properties:
        acks: -1
        delivery.timeout.ms: 90000
        batch.size: 10240
        linger.ms: 100
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
      producer:
        client-id: tanpii.bookpoint
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      security:
        protocol: PLAINTEXT
